export { default as Art } from "./Art"
export { default as Hero } from "./Hero"
export { default as Menu } from "./Menu"
export { default as About } from "./About"
export { default as NavBar } from "./NavBar"
export { default as Cocktails } from "./Cocktails"